Turing/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.views.generic.base import RedirectView
from django.conf.urls.static import static

from engine.views import SignUpView, SignUpClosedView

signup_view = SignUpView if settings.REGISTRATION_OPEN else SignUpClosedView

urlpatterns = [
    path('', RedirectView.as_view(url="engine/")),
    path('admin/', admin.site.urls),
    path('engine/', include('engine.urls')),
    path('accounts/signup/', signup_view.as_view(), name='signup'),
    path('accounts/', include('django.contrib.auth.urls'))
]

if settings.DEV_MODE:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

        # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

engine/urls.py
from django.urls import path

from django.conf import settings
from django.conf.urls.static import static

from engine.views import *

app_name = 'engine'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('gara/new', CreaGaraView.as_view(), name='gara-new'),
    path('gara/upload', UploadGaraView.as_view(), name='gara-upload'),
    path('gara/<int:pk>', GaraView.as_view(), name='gara-detail'),
    path('gara/<int:pk>/admin', GaraAdminView.as_view(), name='gara-admin'),
    path('gara/<int:pk>/parametri', GaraParametriView.as_view(), name='gara-parametri'),
    path('gara/<int:pk>/risposte', GaraRisposteView.as_view(), name='gara-risposte'),
    path('gara/<int:pk>/squadre', GaraSquadreView.as_view(), name='gara-squadre'),
    path('gara/<int:pk>/download', DownloadGaraView.as_view(), name='gara-download'),
    path('query/<int:pk>', QueryView.as_view(), name='query'),
    path('inserisci/<int:pk>', InserimentoView.as_view(), name='inserimento'),
    path('evento/<int:pk>/modifica', ModificaEventoView.as_view(), name='evento-modifica'),
    path('evento/<int:pk>/elimina', EliminaEventoView.as_view(), name='evento-elimina'),
    path('status/<int:pk>', StatusView.as_view(), name='status'),
    path('classifica/<int:pk>/squadre', ClassificaView.as_view(), name='classifica-squadre'),
    path('classifica/<int:pk>/problemi', PuntiProblemiView.as_view(), name='classifica-problemi'),
    path('classifica/<int:pk>/stato', StatoProblemiView.as_view(), name='classifica-stato'),
    path('classifica/<int:pk>/cronaca', CronacaView.as_view(), name='classifica-cronaca'),
    path('classifica/<int:pk>/unica', UnicaView.as_view(), name='classifica-unica'),
    path('about', AboutView.as_view(), name="about")
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

engine/forms.py
from django import forms
from engine.models import User
from django.contrib.auth.forms import UserCreationForm
from crispy_forms.helper import FormHelper

from engine.models import Squadra, Soluzione, Jolly, Consegna

class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')

class RispostaEsattaFormSet(forms.BaseModelFormSet):
    def __init__(self, *args, **kwargs):
        super(RispostaEsattaFormSet, self).__init__(*args, **kwargs)
        no_of_forms = len(self)
        for i in range(0, no_of_forms):
            self[i].fields['risposta'].label += " {}".format(i + 1)
            self[i].fields['problema'].widget = forms.HiddenInput()


RispostaFormset = forms.modelformset_factory(
    Soluzione, fields=('problema', 'risposta', 'nome', 'punteggio'),
    extra=0, formset=RispostaEsattaFormSet,)


class BaseSquadraFormSet(forms.BaseModelFormSet):
    def __init__(self, *args, **kwargs):
        users_qs = kwargs.pop("users_qs")
        super().__init__(*args, **kwargs)
        users_qs.all = lambda: users_qs
        users_qs.iterator = users_qs.all

        # Apply the common (non-cloning) querysets to all the forms
        for form in self.forms:
            form.fields["consegnatore"].queryset = users_qs

    def clean(self, *args, **kwargs):
        if any(self.errors):
            # Don't bother validating the formset unless each form is valid on its own
            return
        squadre = []
        ids = []
        for form in self.forms:
            id = form.cleaned_data["num"]
            sq = form.cleaned_data['nome']
            if sq in squadre:
                raise forms.ValidationError('I nomi delle squadre devono essere distinti!')
            if id in ids:
                raise forms.ValidationError('Gli identificativi delle squadre devono essere unici!')
            squadre.append(sq)
            ids.append(id)


class SquadraForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_class = 'form-inline'
        self.helper.field_template = 'forms/inline_field.html'

    class Meta:
        model = Squadra
        fields = ['num', 'nome', 'ospite', 'consegnatore']


SquadraFormset = forms.modelformset_factory(
                    Squadra, form=SquadraForm,
                    extra=0, formset=BaseSquadraFormSet,)


class SquadraChoiceField(forms.ModelChoiceField):
    def label_from_instance(self, obj):
        return obj.get_id_nome()


class InserimentoForm(forms.Form):
    problema = forms.IntegerField(min_value=1)
    risposta = forms.IntegerField(min_value=0, max_value=9999, required=False)
    jolly = forms.BooleanField(required=False)
    squadra = SquadraChoiceField(required=True, queryset=None)

    def __init__(self, *args, **kwargs):
        self.gara = kwargs.pop('gara', None)
        self.user = kwargs.pop('user', None)
        super(InserimentoForm, self).__init__(*args, **kwargs)
        if self.gara:
            self.fields['squadra'].queryset = self.gara.get_squadre_inseribili(self.user)
            self.fields['squadra'].empty_label = None
            self.fields['squadra'].widget.attrs.update({'autofocus': ''})

    def clean(self):
        cleaned_data = super().clean()
        if self.errors:
            return cleaned_data

        if bool(cleaned_data['jolly']) != bool(cleaned_data['risposta'] is None):
            raise forms.ValidationError('Inserire la risposta o il jolly, ma non entrambi')
        
        if bool(cleaned_data['jolly']) and Jolly.objects.filter(squadra = cleaned_data['squadra']).exists():
            raise forms.ValidationError('Ė già stato inserito un jolly per la squadra')
 
        obj = self.get_instance()
        obj.clean()
        return cleaned_data

    def get_instance(self):
        if self.cleaned_data.get('jolly'):
            return Jolly(gara=self.gara, squadra=self.cleaned_data.get('squadra'),
                         problema=self.cleaned_data.get('problema'))
        else:
            return Consegna(gara=self.gara, squadra=self.cleaned_data.get('squadra'),
                            problema=self.cleaned_data.get('problema'),
                            risposta=self.cleaned_data.get('risposta'))


class ModificaConsegnaForm(forms.Form):
    problema = forms.IntegerField(min_value=1, max_value=50)
    risposta = forms.IntegerField(min_value=0, max_value=9999)


class ModificaJollyForm(forms.Form):
    jolly = forms.IntegerField(min_value=1, max_value=50)


class UploadGaraForm(forms.Form):
    gara = forms.FileField(label="Gara", help_text="Scegli il file JSON contente la gara da importare")

engine/views.py
from django.views.generic import TemplateView, FormView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.urls import reverse
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin, PermissionRequiredMixin
from django.http import JsonResponse, HttpResponse
from django.utils import timezone
from django.db import transaction
from django.contrib.auth import login, authenticate

from engine.models import User, Gara, Soluzione, Squadra, Evento, Consegna, Jolly
from engine.forms import SignUpForm, RispostaFormset, SquadraFormset, InserimentoForm,\
    ModificaConsegnaForm, ModificaJollyForm, UploadGaraForm
from engine.formfields import IntegerMultiField

import json
import time
import logging
logger = logging.getLogger(__name__)


class CheckPermissionsMixin(LoginRequiredMixin, UserPassesTestMixin):
    """
    Mixin che controlla che l'utente sia autenticato e che soddisfi la funzione test_func.
    """
    pass


class IndexView(TemplateView):
    """ Pagina principale """
    template_name = "index.html"


class AboutView(TemplateView):
    """ Pagina 'chi siamo' """
    template_name = "about.html"


class SignUpView(FormView):
    """ Pagina di registrazione """
    form_class = SignUpForm
    template_name = "registration/signup.html"
    success_url = "/engine/"

    def form_valid(self, form):
        user = form.save()
        raw_password = form.cleaned_data.get('password1')
        user = authenticate(username=user.username, password=raw_password)
        login(self.request, user)
        return super().form_valid(form)


class SignUpClosedView(TemplateView):
    """ Pagina per quando la registrazione è disabilitata """
    template_name = "registration/signup_closed.html"


#####################
#    VIEWS GARA     #
#####################

class CreaOModificaGaraView(SuccessMessageMixin):
    """ Superclasse per astrarre metodi comuni a CreaGaraView e ModificaGaraView"""
    model = Gara
    fields = ['nome', 'durata', 'n_blocco', 'k_blocco',
              'num_problemi', 'cutoff', 'fixed_bonus', 'super_mega_bonus', 'jolly', 'testo']

    def get_form(self):
        form = super().get_form()
        # Cambia i campi per i bonus per avere caselle multiple
        form.fields['fixed_bonus'] = IntegerMultiField(
            required=False, require_all_fields=False,
            help_text=form.fields['fixed_bonus'].help_text,
            label=form.fields['fixed_bonus'].label,
            initial=form.fields['fixed_bonus'].initial)
        form.fields['super_mega_bonus'] = IntegerMultiField(
            required=False, require_all_fields=False,
            help_text=form.fields['super_mega_bonus'].help_text,
            label=form.fields['super_mega_bonus'].label,
            initial=form.fields['super_mega_bonus'].initial)
        return form

    def get_success_url(self, **kwargs):
        return reverse("engine:gara-admin", kwargs={'pk': self.object.pk})


class CreaGaraView(PermissionRequiredMixin, CreaOModificaGaraView, CreateView):
    """ View per la creazione di una gara """

    template_name = "gara/create.html"
    success_message = 'Gara creata con successo!'
    permission_required = "engine.add_gara"

    def form_valid(self, form):
        form.instance.admin = self.request.user
        response = super().form_valid(form)
        gara = form.instance
        for i in range(1, gara.num_problemi+1):
            Soluzione.objects.create(gara=gara, problema=i, nome="Problema {}".format(i))
        return response

    def form_invalid(self, form):
        messages.error(self.request, "Errore: gara non creata correttamente")
        return super().form_invalid(form)


class GaraParametriView(CheckPermissionsMixin, CreaOModificaGaraView, UpdateView):
    """ View per cambiare i parametri di una gara """
    template_name = "gara/modify.html"
    success_message = 'Parametri di gara salvati con successo!'

    def test_func(self):
        # Salva la gara dentro self.object, così siamo sicuri
        # che sia stata validata e non viene chiamato get_object() due volte.
        self.object = self.get_object()
        return self.request.user.can_administrate(self.object)

    @transaction.atomic   # visto che creiamo nuovi problemi E aggiorniamo gara.num_problemi
    def form_valid(self, form):
        gara_nuova = form.instance
        gara_vecchia = self.get_object()

        if gara_nuova.num_problemi > gara_vecchia.num_problemi:
            # dobbiamo creare nuovi problemi
            for i in range(gara_vecchia.num_problemi+1, gara_nuova.num_problemi+1):
                Soluzione.objects.create(gara=gara_vecchia, problema=i, nome="Problema {}".format(i))
        elif gara_nuova.num_problemi < gara_vecchia.num_problemi:
            # dobbiamo cancellare problemi
            Soluzione.objects.filter(gara=gara_vecchia, problema__range=(gara_nuova.num_problemi+1, gara_vecchia.num_problemi)).delete()
        response = super().form_valid(form) # committa le modifiche
        return response

    def form_invalid(self, form):
        messages.error(self.request, "Errore: parametri di gara non salvati correttamente")
        return super().form_invalid(form)


class GaraView(DetailView):
    """ View con riepilogo di una gara """
    model = Gara
    template_name = "gara/detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            context["can_insert"] = self.request.user.can_insert_gara(self.object)
            context["is_admin"] = self.request.user.can_administrate(self.object)
        return context


class GaraAdminView(CheckPermissionsMixin, DetailView):
    """ View per l'amministrazione di una gara """
    model = Gara
    template_name = "gara/detail_admin.html"

    def test_func(self):
        # Salva la gara dentro self.object, così siamo sicuri
        # che sia stata validata e non viene chiamato get_object() due volte.
        self.object = self.get_object()
        return self.request.user.can_administrate(self.object)

    def post(self, request, *args, **kwargs):
        if "inizia" in request.POST:
            loraesatta = timezone.now()
            gara = self.object
            gara.inizio = loraesatta
            gara.save()
        return super().get(self, request)


class GaraRisposteView(CheckPermissionsMixin, SuccessMessageMixin, FormView, DetailView):
    """ View per l'inserimento delle soluzioni esatte di una gara """
    model = Gara
    template_name = 'gara/risposte.html'
    success_message = 'Soluzioni inserite con successo!'

    def test_func(self):
        self.object = self.get_object()
        return self.request.user.can_administrate(self.object)

    def get_success_url(self, **kwargs):
        return reverse("engine:gara-admin", kwargs={'pk': self.object.pk})

    def get_form(self):
        if self.request.POST:
            return RispostaFormset(self.request.POST)
        return RispostaFormset(queryset=Soluzione.objects.filter(gara=self.object))

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, "Errore: soluzioni non inserite correttamente")
        return super().form_invalid(form)


class GaraSquadreView(CheckPermissionsMixin, SuccessMessageMixin, FormView, DetailView):
    """ View per l'inserimento delle squadre partecipanti ad una gara """
    model = Gara
    template_name = 'gara/squadre.html'
    success_message = 'Squadre inserite con successo!'

    def test_func(self):
        self.object = self.get_object()
        return self.request.user.can_administrate(self.object)

    def get_success_url(self, **kwargs):
        return reverse("engine:gara-admin", kwargs={'pk': self.object.pk})

    def get_form(self):
        users = User.objects.all()
        if self.request.POST:
            return SquadraFormset(self.request.POST, users_qs=users)
        return SquadraFormset(queryset=self.object.squadre.all(), users_qs=users)

    def form_valid(self, form):
        for res in form.cleaned_data:
            sq = self.object.squadre.filter(num=res['num']).first()
            if sq:
                sq.nome = res['nome']
                sq.ospite = res['ospite']
                sq.consegnatore = res['consegnatore']
            else:
                sq = Squadra(gara=self.object, num=res['num'], nome=res['nome'], ospite=res['ospite'], consegnatore=res['consegnatore'])
            sq.save()
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, "Errore: squadre non inserite correttamente")
        return super().form_invalid(form)


class UploadGaraView(PermissionRequiredMixin, SuccessMessageMixin, FormView):
    """ Importa una gara tramite l'upload di un file JSON """
    form_class = UploadGaraForm
    template_name = "gara/upload.html"
    success_message = "Gara caricata con successo!"
    permission_required = "engine.add_gara"

    def get_success_url(self):
        return reverse("engine:gara-detail", kwargs={'pk': self.gara.pk})

    def form_valid(self, form):
        gara_file = self.request.FILES['gara']
        gara_json = json.load(gara_file)
        self.gara = Gara.create_from_dict(gara_json)
        return super().form_valid(form)


class DownloadGaraView(DetailView):
    """ Serializza la gara e crea un json da scaricare """
    model = Gara

    def get(self, request, *args, **kwargs):
        super().get(request, *args, **kwargs)
        loraesatta = timezone.now()
        if self.object.get_ora_fine() >= loraesatta:
            return HttpResponse('Non puoi scaricare una gara in corso', status=404)
        data = self.object.dump_to_json()

engine/templates/gara/create.html
{% extends "baseheader.html" %}
{% block title %}Crea nuova gara{% endblock %}

{% block content %}

<div class="container">
<h3>Crea una nuova gara</h3>

<form method="post" enctype="multipart/form-data">{% csrf_token %}
    {{ form.non_field_errors }}
    {{ form.errors }}

    {% include 'gara/parametri.html' %}

    <button id="submit" type="submit" class="btn btn-primary">Crea gara</button>
</form>
</div>
{% endblock %}

engine/templates/gara/detail.html
{% extends "basegara.html" %}
{% load static %}
{% block title %}{{object.nome}}{% endblock %}

{% block css %}<link href="{% static 'engine/css/classifiche.css' %}" rel="stylesheet" type="text/css" >{% endblock %}

{% block content %}
<h3>Gara: {{ object.nome }}  {% if is_admin %}<a href="{% url 'engine:gara-admin' object.pk %}" title="Modifica impostazioni di gara"><i class="fas fa-cogs"></i></a>{% endif %}</h3>

{% if object.inizio is not null %}
    <p>
    Iniziata {{object.inizio}};
    {% if not object.finished %}
        finisce {{object.get_ora_fine}}.</p>
        {% if can_insert %}
        <p>Vai all'<a href="{% url 'engine:inserimento' object.pk %}">inserimento risposte</a>.</p>
        {% endif %}
    {% else %}
        finita {{object.get_ora_fine}}.</p>
    {% endif %}

    {% if object.testo %}
    <p>Scarica il testo: <a href="{{object.testo}}" target=_blank><i class="fas fa-file-pdf"></i></a></p>
    {% endif %}
{% else %}
<p>Gara ancora da iniziare</p>
{% endif %}

<h5>Visualizza le classifiche:</h5>

<ul class="pl-0 pl-sm-3 pl-lg-5">
<li class="m-4">
<a class="nohover" href="{% url 'engine:classifica-unica' object.pk %}" target="_blank">
    <b>Visualizzazione unica</b>
    <div class="col-sm-6 col-lg-4 border" style="position: relative">
    <table class="table table-striped table-bordered table-sm mt-2 mb-2">
        <tbody>
            <tr>
              <th scope="row" style="white-space:pre">1°</th>
              <th scope="row" class="text-truncate" style="white-space:pre">Squadra 5</th>
              <th scope="row" style="white-space:pre">1245</th>
                  <td style="text-align: center"></td>
                  <td style="text-align: center" class="right-answer"><b>116</b></td>
                  <td style="text-align: center"></td>
            </tr>
            <tr>
              <th scope="row" style="white-space:pre">2°</th>
              <th scope="row" class="text-truncate" style="white-space:pre">Squadra 2</th>
              <th scope="row" style="white-space:pre">1136</th>
                  <td style="text-align: center" class="right-answer"><b>75</b></td>
                  <td style="text-align: center"></td>
                  <td style="text-align: center" class="wrong-answer"><b>-20</b></td>
            </tr>
        </tbody>
    </table>
    </div>
</a>
</li>

<li class="m-4">
<a class="nohover" href="{% url 'engine:classifica-squadre' object.pk %}" target="_blank">
    <b>Punteggi delle squadre</b>
	    <div class="col-sm-6 col-lg-4 border" style="position: relative">
        <table class="table table-borderless mt-2">
        <tr class="row no-gutters">
            <td class="col-6 small-padding text-truncate font-weight-bold"><span id="label-1">Squadra 1</span></td>
            <td class="col-6 small-padding" >
                <div class="progress">
                    <div id="team-1" class="progress-bar" style="width:50%" role="progressbar"><span id="label-points-1" class="points-value">50</span></div>
                </div>
            </td>
        </tr>

        <tr class="row no-gutters">
            <td class="col-6 small-padding text-truncate font-weight-bold"><span id="label-2">Squadra 2</span></td>
            <td class="col-6 small-padding" >
                <div class="progress">
                    <div id="team-2" class="progress-bar" style="width:20%" role="progressbar"><span id="label-points-2" class="points-value">20</span></div>
                </div>
            </td>
        </tr>

        <tr class="row no-gutters">
            <td class="col-6 small-padding text-truncate font-weight-bold"><span id="label-3">Squadra 3</span></td>
            <td class="col-6 small-padding" >
                <div class="progress">
                    <div id="team-3" class="progress-bar" style="width:100%" role="progressbar"><span id="label-points-3" class="points-value">100</span></div>
                </div>
            </td>
        </tr>
	    </table>
		</div>
</a>
</li>

<li class="m-4">
<a class="nohover" href="{% url 'engine:classifica-problemi' object.pk %}" target="_blank">
    <b>Punteggi dei problemi</b>
	<div class="col-sm-6 col-lg-4 border" style="position: relative">
	<table class="table table-borderless mt-2">
	<tr class="row no-gutters">
	    <td class="col-6 small-padding text-truncate font-weight-bold"><span id="label-1">Problema 1</span></td>
	    <td class="col-6 small-padding align-self-center">
	        <div class="progress">
	            <div id="punti-1" class="progress-bar progress-bar-striped" role="progressbar" style="width:50%"><span id="label-punti-1" class="points-value">50</span></div>
	            <div id="bonus-1" class="progress-bar bg-warning" role="progressbar" style="width:20%"><span id="label-bonus-1" class="points-value">20</span></div>
	        </div>
	    </td>
	</tr>

	<tr class="row no-gutters">
	    <td class="col-6 small-padding text-truncate font-weight-bold"><span id="label-2">Problema 2</span></td>
	    <td class="col-6 small-padding align-self-center">
	        <div class="progress">
	            <div id="punti-2" class="progress-bar progress-bar-striped" role="progressbar" style="width:80%"><span id="label-punti-2" class="points-value">80</span></div>
	            <div id="bonus-2" class="progress-bar bg-warning" role="progressbar" style="width:15%"><span id="label-bonus-2" class="points-value">15</span></div>
	        </div>
	    </td>
	</tr>

	<tr class="row no-gutters">
	    <td class="col-6 small-padding text-truncate font-weight-bold"><span id="label-3">Problema 3</span></td>
	    <td class="col-6 small-padding align-self-center">
	        <div class="progress">
	            <div id="punti-3" class="progress-bar progress-bar-striped" role="progressbar" style="width:40%"><span id="label-punti-3" class="points-value">40</span></div>
	            <div id="bonus-3" class="progress-bar bg-warning" role="progressbar" style="width:10%"><span id="label-bonus-3" class="points-value">10</span></div>
	        </div>
	    </td>
	</tr>
	</table>
	</div>
</a>
</li>

<li class="m-4">
<a class="nohover" href="{% url 'engine:classifica-stato' object.pk %}" target="_blank">
    <b>Stato delle risposte</b>
	    <div class="col-sm-6 col-lg-4 border" style="position: relative">
	    <table class="table table-striped table-bordered table-sm mt-2 mb-2" style="table-layout:fixed">
        <tbody>
            <tr>
                <th scope="row" class="small-padding text-truncate" style="width:35%">Squadra 1</th>
                  <td class="wrong-answer text-center"><b>1</b><span class="my-fa-stack">
                        <i class="fas fa-star fa-stack-1x fa-inverse" style="color:yellow"></i>
                        <i class="far fa-star fa-stack-1x" style="color:black"></i>
                    </span></td>
                  <td class=""></td>
                  <td class="right-answer"></td>
            </tr>
            <tr>
                <th scope="row" class="small-padding text-truncate">Squadra 2</th>
                  <td class=""></td>
                  <td class="right-answer"></td>
                  <td class="right-answer"></td>
            </tr>
        </tbody>
        </table>
	</div>
</a>
</li>

<li class="m-4">
<a class="nohover" href="{% url 'engine:classifica-cronaca' object.pk %}" target="_blank">
    <b>Telecronaca</b>
    <div class="col-sm-6 col-lg-4 border" style="position: relative">
        <div class="card">
        <div class="card-header">Telecronaca</div>
        <ul id="frasi" class="list-group list-group-flush" >
            <li class="list-group-item">La squadra 5 vince la finale a squadre!</li>
            <li class="list-group-item">La squadra 2 sbaglia e scende in seconda posizione.</li>
        </ul>
        </div>
    </div>
</a>
</li>
</ul>

{% endblock %}

engine/templates/gara/detail_admin.html
{% extends "basegara.html" %}
{% block title %}{{object.nome}} admin{% endblock %}

{% block content %}
<h3>Gara: <a href="{% url 'engine:gara-detail' object.pk %}">{{ object.nome }}</a></h3>


<h5><a href="{% url 'engine:gara-parametri' object.pk %}"> <i class="fas fa-cog"></i> Parametri</a></h5>
<h5><a href="{% url 'engine:gara-risposte' object.pk %}"> <i class="fas fa-tasks"></i> Soluzioni</a><br/></h5>
<h5><a href="{% url 'engine:gara-squadre' object.pk %}"> <i class="fas fa-users"></i> Squadre</a><br/></h5>
{% if object.inizio is not null %}
<h5><a href="{% url 'engine:query' object.pk %}"> <i class="fas fa-database"></i> Query</a><br/></h5>
{% endif %}

<p>
{% if object.inizio is not null %}
Iniziata {{object.inizio}};
{% if not object.finished %}
finisce {{object.get_ora_fine}}.
{% else %}
finita {{object.get_ora_fine}}.
{% endif %}
</p>

<p>Vai all'<a href="{% url 'engine:inserimento' object.pk %}">inserimento risposte</a>.</p>


{% else %}
<p>
Gara ancora da iniziare<br/>
<form method="post">{% csrf_token %}
    <input type="hidden" name="inizia" value=1>
    <input type="submit" value="Inizia la gara" id="submit">
</form>
</p>
{% endif %}

{% endblock %}

engine/templates/gara/modify.html
{% extends "basegara.html" %}
{% block title %}Modifica parametri di gara{% endblock %}

{% block content %}

<div class="container">
<h3>Modifica parametri di gara</h3>

<form method="post" enctype="multipart/form-data">{% csrf_token %}
    {{ form.non_field_errors }}
    {{ form.errors }}

    {% include 'gara/parametri.html' %}

    <button id="submit" type="submit" class="btn btn-primary">Salva modifiche</button>
</form>
</div>
{% endblock %}

engine/templates/gara/parametri.html
{% load crispy_forms_tags %}

    <div class="form-row">
        <div class="form-group col-md-6">
            {{ form.nome|as_crispy_field }}
        </div>
        <div class="col-md-3 form-group">
            {{ form.num_problemi|as_crispy_field }}
        </div>
        <div class="col-md-3 form-group">
            {{ form.durata|as_crispy_field }}
        </div>
    </div>
    <div class="form-row">
        <div class="col-md-4 form-group">
            {{ form.n_blocco|as_crispy_field }}
        </div>
        <div class="col-md-4 form-group">
            {{ form.k_blocco|as_crispy_field }}
        </div>
        <div class="col-md-4 form-group">
            {{ form.cutoff|as_crispy_field }}
        </div>
    </div>
    <div class="form-row">
        <div class="col-md-6 form-group">
            {{ form.fixed_bonus|as_crispy_field }}
        </div>
        <div class="col-md-6 form-group">
            {{ form.super_mega_bonus|as_crispy_field }}
        </div>
    </div>
    {{ form.jolly|as_crispy_field }}
    {{ form.testo|as_crispy_field }}