Turing/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.views.generic.base import RedirectView
from django.conf.urls.static import static

from engine.views import SignUpView, SignUpClosedView

signup_view = SignUpView if settings.REGISTRATION_OPEN else SignUpClosedView

urlpatterns = [
    path('', RedirectView.as_view(url="engine/")),
    path('admin/', admin.site.urls),
    path('engine/', include('engine.urls')),
    path('accounts/signup/', signup_view.as_view(), name='signup'),
    path('accounts/', include('django.contrib.auth.urls'))
]

if settings.DEV_MODE:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

        # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

engine/urls.py
from django.urls import path

from django.conf import settings
from django.conf.urls.static import static

from engine.views import *

app_name = 'engine'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('gara/new', CreaGaraView.as_view(), name='gara-new'),
    path('gara/upload', UploadGaraView.as_view(), name='gara-upload'),
    path('gara/<int:pk>', GaraView.as_view(), name='gara-detail'),
    path('gara/<int:pk>/admin', GaraAdminView.as_view(), name='gara-admin'),
    path('gara/<int:pk>/parametri', GaraParametriView.as_view(), name='gara-parametri'),
    path('gara/<int:pk>/risposte', GaraRisposteView.as_view(), name='gara-risposte'),
    path('gara/<int:pk>/squadre', GaraSquadreView.as_view(), name='gara-squadre'),
    path('gara/<int:pk>/download', DownloadGaraView.as_view(), name='gara-download'),
    path('query/<int:pk>', QueryView.as_view(), name='query'),
    path('inserisci/<int:pk>', InserimentoView.as_view(), name='inserimento'),
    path('evento/<int:pk>/modifica', ModificaEventoView.as_view(), name='evento-modifica'),
    path('evento/<int:pk>/elimina', EliminaEventoView.as_view(), name='evento-elimina'),
    path('status/<int:pk>', StatusView.as_view(), name='status'),
    path('classifica/<int:pk>/squadre', ClassificaView.as_view(), name='classifica-squadre'),
    path('classifica/<int:pk>/problemi', PuntiProblemiView.as_view(), name='classifica-problemi'),
    path('classifica/<int:pk>/stato', StatoProblemiView.as_view(), name='classifica-stato'),
    path('classifica/<int:pk>/cronaca', CronacaView.as_view(), name='classifica-cronaca'),
    path('classifica/<int:pk>/unica', UnicaView.as_view(), name='classifica-unica'),
    path('about', AboutView.as_view(), name="about")
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

engine/forms.py
from django import forms
from engine.models import User
from django.contrib.auth.forms import UserCreationForm
from crispy_forms.helper import FormHelper

from engine.models import Squadra, Soluzione, Jolly, Consegna

class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')

class RispostaEsattaFormSet(forms.BaseModelFormSet):
    def __init__(self, *args, **kwargs):
        super(RispostaEsattaFormSet, self).__init__(*args, **kwargs)
        no_of_forms = len(self)
        for i in range(0, no_of_forms):
            self[i].fields['risposta'].label += " {}".format(i + 1)
            self[i].fields['problema'].widget = forms.HiddenInput()


RispostaFormset = forms.modelformset_factory(
    Soluzione, fields=('problema', 'risposta', 'nome', 'punteggio'),
    extra=0, formset=RispostaEsattaFormSet,)


class BaseSquadraFormSet(forms.BaseModelFormSet):
    def __init__(self, *args, **kwargs):
        users_qs = kwargs.pop("users_qs")
        super().__init__(*args, **kwargs)
        users_qs.all = lambda: users_qs
        users_qs.iterator = users_qs.all

        # Apply the common (non-cloning) querysets to all the forms
        for form in self.forms:
            form.fields["consegnatore"].queryset = users_qs

    def clean(self, *args, **kwargs):
        if any(self.errors):
            # Don't bother validating the formset unless each form is valid on its own
            return
        squadre = []
        ids = []
        for form in self.forms:
            id = form.cleaned_data["num"]
            sq = form.cleaned_data['nome']
            if sq in squadre:
                raise forms.ValidationError('I nomi delle squadre devono essere distinti!')
            if id in ids:
                raise forms.ValidationError('Gli identificativi delle squadre devono essere unici!')
            squadre.append(sq)
            ids.append(id)


class SquadraForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_class = 'form-inline'
        self.helper.field_template = 'forms/inline_field.html'

    class Meta:
        model = Squadra
        fields = ['num', 'nome', 'ospite', 'consegnatore']


SquadraFormset = forms.modelformset_factory(
                    Squadra, form=SquadraForm,
                    extra=0, formset=BaseSquadraFormSet,)


class SquadraChoiceField(forms.ModelChoiceField):
    def label_from_instance(self, obj):
        return obj.get_id_nome()


class InserimentoForm(forms.Form):
    problema = forms.IntegerField(min_value=1)
    risposta = forms.IntegerField(min_value=0, max_value=9999, required=False)
    jolly = forms.BooleanField(required=False)
    squadra = SquadraChoiceField(required=True, queryset=None)

    def __init__(self, *args, **kwargs):
        self.gara = kwargs.pop('gara', None)
        self.user = kwargs.pop('user', None)
        super(InserimentoForm, self).__init__(*args, **kwargs)
        if self.gara:
            self.fields['squadra'].queryset = self.gara.get_squadre_inseribili(self.user)
            self.fields['squadra'].empty_label = None
            self.fields['squadra'].widget.attrs.update({'autofocus': ''})

    def clean(self):
        cleaned_data = super().clean()
        if self.errors:
            return cleaned_data

        if bool(cleaned_data['jolly']) != bool(cleaned_data['risposta'] is None):
            raise forms.ValidationError('Inserire la risposta o il jolly, ma non entrambi')
        
        if bool(cleaned_data['jolly']) and Jolly.objects.filter(squadra = cleaned_data['squadra']).exists():
            raise forms.ValidationError('Ė già stato inserito un jolly per la squadra')
 
        obj = self.get_instance()
        obj.clean()
        return cleaned_data

    def get_instance(self):
        if self.cleaned_data.get('jolly'):
            return Jolly(gara=self.gara, squadra=self.cleaned_data.get('squadra'),
                         problema=self.cleaned_data.get('problema'))
        else:
            return Consegna(gara=self.gara, squadra=self.cleaned_data.get('squadra'),
                            problema=self.cleaned_data.get('problema'),
                            risposta=self.cleaned_data.get('risposta'))


class ModificaConsegnaForm(forms.Form):
    problema = forms.IntegerField(min_value=1, max_value=50)
    risposta = forms.IntegerField(min_value=0, max_value=9999)


class ModificaJollyForm(forms.Form):
    jolly = forms.IntegerField(min_value=1, max_value=50)


class UploadGaraForm(forms.Form):
    gara = forms.FileField(label="Gara", help_text="Scegli il file JSON contente la gara da importare")

engine/views.py
from django.views.generic import TemplateView, FormView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.urls import reverse
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin, PermissionRequiredMixin
from django.http import JsonResponse, HttpResponse
from django.utils import timezone
from django.db import transaction
from django.contrib.auth import login, authenticate

from engine.models import User, Gara, Soluzione, Squadra, Evento, Consegna, Jolly
from engine.forms import SignUpForm, RispostaFormset, SquadraFormset, InserimentoForm,\
    ModificaConsegnaForm, ModificaJollyForm, UploadGaraForm
from engine.formfields import IntegerMultiField

import json
import time
import logging
logger = logging.getLogger(__name__)


class CheckPermissionsMixin(LoginRequiredMixin, UserPassesTestMixin):
    """
    Mixin che controlla che l'utente sia autenticato e che soddisfi la funzione test_func.
    """
    pass


class IndexView(TemplateView):
    """ Pagina principale """
    template_name = "index.html"


class AboutView(TemplateView):
    """ Pagina 'chi siamo' """
    template_name = "about.html"


class SignUpView(FormView):
    """ Pagina di registrazione """
    form_class = SignUpForm
    template_name = "registration/signup.html"
    success_url = "/engine/"

    def form_valid(self, form):
        user = form.save()
        raw_password = form.cleaned_data.get('password1')
        user = authenticate(username=user.username, password=raw_password)
        login(self.request, user)
        return super().form_valid(form)


class SignUpClosedView(TemplateView):
    """ Pagina per quando la registrazione è disabilitata """
    template_name = "registration/signup_closed.html"


#####################
#    VIEWS GARA     #
#####################

class CreaOModificaGaraView(SuccessMessageMixin):
    """ Superclasse per astrarre metodi comuni a CreaGaraView e ModificaGaraView"""
    model = Gara
    fields = ['nome', 'durata', 'n_blocco', 'k_blocco',
              'num_problemi', 'cutoff', 'fixed_bonus', 'super_mega_bonus', 'jolly', 'testo']

    def get_form(self):
        form = super().get_form()
        # Cambia i campi per i bonus per avere caselle multiple
        form.fields['fixed_bonus'] = IntegerMultiField(
            required=False, require_all_fields=False,
            help_text=form.fields['fixed_bonus'].help_text,
            label=form.fields['fixed_bonus'].label,
            initial=form.fields['fixed_bonus'].initial)
        form.fields['super_mega_bonus'] = IntegerMultiField(
            required=False, require_all_fields=False,
            help_text=form.fields['super_mega_bonus'].help_text,
            label=form.fields['super_mega_bonus'].label,
            initial=form.fields['super_mega_bonus'].initial)
        return form

    def get_success_url(self, **kwargs):
        return reverse("engine:gara-admin", kwargs={'pk': self.object.pk})


class CreaGaraView(PermissionRequiredMixin, CreaOModificaGaraView, CreateView):
    """ View per la creazione di una gara """

    template_name = "gara/create.html"
    success_message = 'Gara creata con successo!'
    permission_required = "engine.add_gara"

    def form_valid(self, form):
        form.instance.admin = self.request.user
        response = super().form_valid(form)
        gara = form.instance
        for i in range(1, gara.num_problemi+1):
            Soluzione.objects.create(gara=gara, problema=i, nome="Problema {}".format(i))
        return response

    def form_invalid(self, form):
        messages.error(self.request, "Errore: gara non creata correttamente")
        return super().form_invalid(form)


class GaraParametriView(CheckPermissionsMixin, CreaOModificaGaraView, UpdateView):
    """ View per cambiare i parametri di una gara """
    template_name = "gara/modify.html"
    success_message = 'Parametri di gara salvati con successo!'

    def test_func(self):
        # Salva la gara dentro self.object, così siamo sicuri
        # che sia stata validata e non viene chiamato get_object() due volte.
        self.object = self.get_object()
        return self.request.user.can_administrate(self.object)

    @transaction.atomic   # visto che creiamo nuovi problemi E aggiorniamo gara.num_problemi
    def form_valid(self, form):
        gara_nuova = form.instance
        gara_vecchia = self.get_object()

        if gara_nuova.num_problemi > gara_vecchia.num_problemi:
            # dobbiamo creare nuovi problemi
            for i in range(gara_vecchia.num_problemi+1, gara_nuova.num_problemi+1):
                Soluzione.objects.create(gara=gara_vecchia, problema=i, nome="Problema {}".format(i))
        elif gara_nuova.num_problemi < gara_vecchia.num_problemi:
            # dobbiamo cancellare problemi
            Soluzione.objects.filter(gara=gara_vecchia, problema__range=(gara_nuova.num_problemi+1, gara_vecchia.num_problemi)).delete()
        response = super().form_valid(form) # committa le modifiche
        return response

    def form_invalid(self, form):
        messages.error(self.request, "Errore: parametri di gara non salvati correttamente")
        return super().form_invalid(form)


class GaraView(DetailView):
    """ View con riepilogo di una gara """
    model = Gara
    template_name = "gara/detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            context["can_insert"] = self.request.user.can_insert_gara(self.object)
            context["is_admin"] = self.request.user.can_administrate(self.object)
        return context


class GaraAdminView(CheckPermissionsMixin, DetailView):
    """ View per l'amministrazione di una gara """
    model = Gara
    template_name = "gara/detail_admin.html"

    def test_func(self):
        # Salva la gara dentro self.object, così siamo sicuri
        # che sia stata validata e non viene chiamato get_object() due volte.
        self.object = self.get_object()
        return self.request.user.can_administrate(self.object)

    def post(self, request, *args, **kwargs):
        if "inizia" in request.POST:
            loraesatta = timezone.now()
            gara = self.object
            gara.inizio = loraesatta
            gara.save()
        return super().get(self, request)


class GaraRisposteView(CheckPermissionsMixin, SuccessMessageMixin, FormView, DetailView):
    """ View per l'inserimento delle soluzioni esatte di una gara """
    model = Gara
    template_name = 'gara/risposte.html'
    success_message = 'Soluzioni inserite con successo!'

    def test_func(self):
        self.object = self.get_object()
        return self.request.user.can_administrate(self.object)

    def get_success_url(self, **kwargs):
        return reverse("engine:gara-admin", kwargs={'pk': self.object.pk})

    def get_form(self):
        if self.request.POST:
            return RispostaFormset(self.request.POST)
        return RispostaFormset(queryset=Soluzione.objects.filter(gara=self.object))

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, "Errore: soluzioni non inserite correttamente")
        return super().form_invalid(form)


class GaraSquadreView(CheckPermissionsMixin, SuccessMessageMixin, FormView, DetailView):
    """ View per l'inserimento delle squadre partecipanti ad una gara """
    model = Gara
    template_name = 'gara/squadre.html'
    success_message = 'Squadre inserite con successo!'

    def test_func(self):
        self.object = self.get_object()
        return self.request.user.can_administrate(self.object)

    def get_success_url(self, **kwargs):
        return reverse("engine:gara-admin", kwargs={'pk': self.object.pk})

    def get_form(self):
        users = User.objects.all()
        if self.request.POST:
            return SquadraFormset(self.request.POST, users_qs=users)
        return SquadraFormset(queryset=self.object.squadre.all(), users_qs=users)

    def form_valid(self, form):
        for res in form.cleaned_data:
            sq = self.object.squadre.filter(num=res['num']).first()
            if sq:
                sq.nome = res['nome']
                sq.ospite = res['ospite']
                sq.consegnatore = res['consegnatore']
            else:
                sq = Squadra(gara=self.object, num=res['num'], nome=res['nome'], ospite=res['ospite'], consegnatore=res['consegnatore'])
            sq.save()
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, "Errore: squadre non inserite correttamente")
        return super().form_invalid(form)


class UploadGaraView(PermissionRequiredMixin, SuccessMessageMixin, FormView):
    """ Importa una gara tramite l'upload di un file JSON """
    form_class = UploadGaraForm
    template_name = "gara/upload.html"
    success_message = "Gara caricata con successo!"
    permission_required = "engine.add_gara"

    def get_success_url(self):
        return reverse("engine:gara-detail", kwargs={'pk': self.gara.pk})

    def form_valid(self, form):
        gara_file = self.request.FILES['gara']
        gara_json = json.load(gara_file)
        self.gara = Gara.create_from_dict(gara_json)
        return super().form_valid(form)


class DownloadGaraView(DetailView):
    """ Serializza la gara e crea un json da scaricare """
    model = Gara

    def get(self, request, *args, **kwargs):
        super().get(request, *args, **kwargs)
        loraesatta = timezone.now()
        if self.object.get_ora_fine() >= loraesatta:
            return HttpResponse('Non puoi scaricare una gara in corso', status=404)
        data = self.object.dump_to_json()

engine/templates/classifiche/class_template.html
{% extends "base.html" %}
{% load static %}

{% block head %}
<script src="{% static "engine/js/client.js" %}"></script>
{% endblock %}

{% block css %}<link href="{% static 'engine/css/classifiche.css' %}" rel="stylesheet" type="text/css" >{% endblock %}

{% block content %}
{% if object.inizio is not null %}
{% block main %}{% endblock %}

<script>
document.updated = false;
document.addEventListener("updated", function(e) {
  document.updated = true;
});
$(document).ready(function() {
    var url = "{% url 'engine:status' object.pk %}";
    var client = new ClassificaClient(url, '{% block class_type %}{% endblock %}');
    client.init();
    {% if object.finished %}
    $("#myRange").on('input', function() {
        client.progress = this.value/1000;
    });
    $("#play").click(function() {
        client.toggleReplay(this, "myRange")
    });

    {% else %}
    setInterval(function() {client.update()}, 3000);
    {% endif %}
});

</script>
{% else %}
<p>La classifica non è disponibile prima dell'inizio della gara</p>
{% endif %}
{% endblock %}

engine/templates/classifiche/cronaca.html
{% extends "classifiche/class_template.html" %}
{% load static %}
{% block title %}Cronaca {{object.nome}}{% endblock %}

{% block class_type %}cronaca{% endblock %}

{% block head %}
{{ block.super }}
<script src="{% static "vendor/jquery-easing/jquery.easing.min.js" %}"></script>
{% endblock %}

{% block main %}
<h3>Gara: <a href="{% url 'engine:gara-detail' object.pk %}">{{object.nome}}</a> - cronaca</h3>
<div class="container-fluid" id="cronaca_main">
    <div class="row no-gutters justify-content-end">
        <h3 id="orologio">##:##:##</h3>
    </div>
    <div class="row">
        <div class="col-lg-9">
            {% for sq in object.get_squadre_order %}
            <div class="row no-gutters" id="div-{{sq.num}}">
                <div class="col-4 col-md-2 small-padding text-truncate font-weight-bold" ><span id="label-{{sq.num}}"></span></div>
                <div class="col-8 col-md-10 small-padding">
                    <div class="progress">
                        <div id="team-{{sq.num}}" class="progress-bar{% if sq.ospite %} ospite{% endif %}" style="width:30%" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"><span id="label-points-{{sq.num}}" class="points-value">0</span></div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        <div class="col-lg-3">
            <div class="card">
            <div class="card-header">Telecronaca</div>
            <ul id="frasi" class="list-group list-group-flush" >
                <li class="list-group-item">Stiamo aspettando di partire...</li>
            </ul>
            </div>
        </div>
    </div>

    {% if object.finished %}
    <div class="row pt-3 no-gutters">
        <input type="range" min="0" max="1000" value="1000"  id="myRange">
        <button id="play" class="ml-2"><i class="fas fa-play"></i></button>
    </div>
    {% endif %}

</div>
{% endblock %}

engine/templates/classifiche/punti_problemi.html
{% extends "classifiche/class_template.html" %}

{% block title %}Problemi {{object.nome}}{% endblock %}

{% block class_type %}problemi{% endblock %}

{% block main %}
<div class="container">
    <h3>Gara: <a href="{% url 'engine:gara-detail' object.pk %}">{{object.nome}}</a> - punteggio problemi</h3>

    <div class="row no-gutters justify-content-end">
        <h3 id="orologio">##:##:##</h3>
    </div>
    <table class="table table-borderless table-sm">
    {% for s in soluzioni %}
    <tr class="row">
        <td class="col-7 col-sm-4 col-lg-2 text-truncate font-weight-bold"><span id="label-{{s.problema}}"></span></span></td>
        <td class="col-sm-8 col-lg-10 small-padding d-none d-sm-block">
            <div class="progress">
                <div id="punti-{{s.problema}}" class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="animation-direction:reverse"><span id="label-punti-{{s.problema}}" class="points-value"></span></div>
                <div id="bonus-{{s.problema}}" class="progress-bar bg-warning" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"><span id="label-bonus-{{s.problema}}" class="points-value"></span></div>
            </div>
        </td>
        <td class="col-5 d-sm-none small-padding" >
            <span id="label-punti-mobile-{{s.problema}}" class="points-value">0</span>
        </td>
    </tr>
    {% endfor %}
    </table>

    {% if object.finished %}
    <div class="row pt-3  no-gutters">
        <input type="range" min="0" max="1000" value="1000"  id="myRange">
        <button id="play" class="ml-2"><i class="fas fa-play"></i></button>
    </div>
    {% endif %}

</div>
{% endblock %}

engine/templates/classifiche/squadre.html
{% extends "classifiche/class_template.html" %}

{% block title %}Classifica {{object.nome}}{% endblock %}

{% block class_type %}squadre{% endblock %}

{% block main %}
<h3>Gara: <a href="{% url 'engine:gara-detail' object.pk %}">{{object.nome}}</a> - classifica</h3>
<div class="container-fluid">
    <div class="row no-gutters justify-content-end">
        <h3 id="orologio">##:##:##</h3>
    </div>
    <div class="row" id="classifica-container" style="position: relative">
        {% comment %}<div id="cutoff"></div>{% endcomment %}
        <table class="table table-borderless">
        {% for sq in object.get_squadre_order %}
        <tr class="row no-gutters">
            <td class="col-7 col-sm-4 col-lg-2 small-padding text-truncate font-weight-bold">
                <span id="label-pos-{{sq.num}}" style="display: inline-block; min-width: 3em;"></span>
                <span id="label-{{sq.num}}">{{sq.nome}}</span>
            </td>
            <td class="col-sm-8 col-lg-10 small-padding d-none d-sm-block" >
                <div class="progress">
                    <div id="team-{{sq.num}}" class="progress-bar{% if sq.ospite %} ospite{% endif %}" style="width:50%" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"><span id="label-points-{{sq.num}}" class="points-value">0</span></div>
                </div>
            </td>
            <td class="col-5 d-sm-none small-padding" >
                <span id="label-points-mobile-{{sq.num}}" class="points-value">0</span>
            </td>
        </tr>
        {% endfor %}

        </table>
    </div>


    {% if object.finished %}
    <div class="row pt-3 no-gutters">
        <input type="range" min="0" max="1000" value="1000"  id="myRange">
        <button id="play" class="ml-2"><i class="fas fa-play"></i></button>
    </div>
    {% endif %}

</div>
{% endblock %}

engine/templates/classifiche/stato_problemi.html
{% extends "classifiche/class_template.html" %}

{% block title %}Stato {{object.nome}}{% endblock %}

{% block class_type %}stato{% endblock %}

{% block main %}
<h3>Gara: <a href="{% url 'engine:gara-detail' object.pk %}">{{ object.nome }}</a> - Stato problemi</h3>

<div class="container-fluid">
    <div class="row no-gutters justify-content-end">
        <h3 id="orologio">##:##:##</h3>
    </div>
    <div class="table-responsive">
    <table class="table table-striped table-bordered table-sm maybe-fixed text-center">
        <thead class="thead-light"><tr>
            <th scope="col" style="width:10%">Sq.</th>
            {% for s in soluzioni %}
            <th scope="col">#{{s.problema|stringformat:"02d"}}</th>
            {% endfor %}
        </tr></thead>
        <tbody>
            {% for sq in object.get_squadre_order %}
            <tr id="riga-{{sq.num}}">
                <th scope="row" class="text-truncate squadra {% if sq.ospite %}text-muted{% endif %}">{{sq.nome}}</th>
                {% for s in soluzioni %}
                  <td id="cell-{{sq.num}}-{{s.problema}}"></td>
                {% endfor %}
            </tr>
            {% endfor %}
        </tbody>
    </table>
    </div>

    {% if object.finished %}
    <div class="row pt-3 no-gutters">
        <input type="range" min="0" max="1000" value="1000"  id="myRange">
        <button id="play" class="ml-2"><i class="fas fa-play"></i></button>
    </div>
    {% endif %}

</div>
{% endblock %}

engine/templates/classifiche/unica.html
{% extends "classifiche/class_template.html" %}

{% block title %}Schermata unica {{object.nome}}{% endblock %}

{% block class_type %}unica{% endblock %}

{% block main %}
<h3>Gara: <a href="{% url 'engine:gara-detail' object.pk %}">{{object.nome}}</a> - visualizzazione unica</h3>
<div class="container-fluid">
  <div class="row no-gutters justify-content-end">
      <h3 id="orologio">##:##:##</h3>
  </div>
    <div class="table-responsive">
    <table class="table table-striped table-bordered table-sm maybe-fixed text-center">
        <thead class="thead-light"><tr>
            <th scope="col" style="width:2.5%">Pos.</th>
            <th scope="col" style="width:8%">Squadra</th>
            <th scope="col" style="width:3%">Punt.</th>
            {% for s in soluzioni %}
            <th scope="col" style="white-space:pre" id="pr-{{s.problema}}">#{{s.problema|stringformat:"02d"}}</th>
            {% endfor %}
        </tr></thead>
        <tbody>
            {% for sq in object.get_squadre_order %}
            <tr id="riga-{{sq.num}}">
              <th scope="row" style="white-space:pre" id="pos-{{sq.num}}">1°</th>
              <th scope="row" class="text-truncate squadra" style="white-space:pre" id="nome-{{sq.num}}">{{sq.nome}}</th>
              <th scope="row" style="white-space:pre" id="punt-{{sq.num}}"></th>
                {% for s in soluzioni %}
                  <td id="cell-{{sq.num}}-{{s.problema}}"></td>
                {% endfor %}
            </tr>
            {% endfor %}
        </tbody>
    </table>
    </div>

    {% if object.finished %}
    <div class="row pt-3 no-gutters">
        <input type="range" min="0" max="1000" value="1000"  id="myRange">
        <button id="play" class="ml-2"><i class="fas fa-play"></i></button>
    </div>
    {% endif %}

</div>
{% endblock %}