Turing/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.views.generic.base import RedirectView
from django.conf.urls.static import static

from engine.views import SignUpView, SignUpClosedView

signup_view = SignUpView if settings.REGISTRATION_OPEN else SignUpClosedView

urlpatterns = [
    path('', RedirectView.as_view(url="engine/")),
    path('admin/', admin.site.urls),
    path('engine/', include('engine.urls')),
    path('accounts/signup/', signup_view.as_view(), name='signup'),
    path('accounts/', include('django.contrib.auth.urls'))
]

if settings.DEV_MODE:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

        # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

engine/urls.py
from django.urls import path

from django.conf import settings
from django.conf.urls.static import static

from engine.views import *

app_name = 'engine'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('gara/new', CreaGaraView.as_view(), name='gara-new'),
    path('gara/upload', UploadGaraView.as_view(), name='gara-upload'),
    path('gara/<int:pk>', GaraView.as_view(), name='gara-detail'),
    path('gara/<int:pk>/admin', GaraAdminView.as_view(), name='gara-admin'),
    path('gara/<int:pk>/parametri', GaraParametriView.as_view(), name='gara-parametri'),
    path('gara/<int:pk>/risposte', GaraRisposteView.as_view(), name='gara-risposte'),
    path('gara/<int:pk>/squadre', GaraSquadreView.as_view(), name='gara-squadre'),
    path('gara/<int:pk>/download', DownloadGaraView.as_view(), name='gara-download'),
    path('query/<int:pk>', QueryView.as_view(), name='query'),
    path('inserisci/<int:pk>', InserimentoView.as_view(), name='inserimento'),
    path('evento/<int:pk>/modifica', ModificaEventoView.as_view(), name='evento-modifica'),
    path('evento/<int:pk>/elimina', EliminaEventoView.as_view(), name='evento-elimina'),
    path('status/<int:pk>', StatusView.as_view(), name='status'),
    path('classifica/<int:pk>/squadre', ClassificaView.as_view(), name='classifica-squadre'),
    path('classifica/<int:pk>/problemi', PuntiProblemiView.as_view(), name='classifica-problemi'),
    path('classifica/<int:pk>/stato', StatoProblemiView.as_view(), name='classifica-stato'),
    path('classifica/<int:pk>/cronaca', CronacaView.as_view(), name='classifica-cronaca'),
    path('classifica/<int:pk>/unica', UnicaView.as_view(), name='classifica-unica'),
    path('about', AboutView.as_view(), name="about")
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

engine/models.py
from django.db import models
from django.core.exceptions import ValidationError, PermissionDenied
from django.core.validators import MaxValueValidator
from django.utils import timezone, dateparse
from django.contrib.auth.models import AbstractUser
from simple_history.models import HistoricalRecords

from datetime import timedelta, date, time
import json
import uuid
from dateutil.parser import parse

import logging
logger = logging.getLogger(__name__)


def get_file_path(instance, filename):  # pragma: no cover
    ext = filename.split('.')[-1]
    filename = "%s.%s" % (uuid.uuid4(), ext)
    return 'testi/'+filename


def str2arr(s):
    if s == "":
        return []
    return [int(x) for x in s.split(',')]


def all_nonnegative_validator(val):
    arr = str2arr(val)
    if not all(x>=0 for x in arr):
        raise ValidationError("Gli interi devono essere tutti non negativi")

class User(AbstractUser):
    GENDERS = (
        ('M', 'Maschio'),
        ('F', 'Femmina'),
        ('N', 'Non specificato'),
    )
    gender = models.CharField(max_length=1, choices=GENDERS, default='N', verbose_name='Genere')

    def can_administrate(self, gara):
        return gara.admin == self

    def is_inseritore(self, gara):
        return self in gara.inseritori.all()

    def is_consegnatore(self, gara):
        return Squadra.objects.filter(gara=gara, consegnatore=self).exists()

    def can_insert_gara(self, gara):
        """Controlla che l'utente sia un admin, un inseritore o un consegnatore"""
        return self.can_administrate(gara) or self.is_inseritore(gara) or self.is_consegnatore(gara)

    def can_insert_squadra(self, squadra):
        """Controlla che l'utente sia un admin, un inseritore o un consegnatore"""
        return self.can_administrate(squadra.gara) or self.is_inseritore(squadra.gara) or squadra.consegnatore == self

    def can_edit_or_delete(self, evento):
        """Controlla che l'utente sia admin, o un inseritore proprietario dell'evento."""
        return self.can_administrate(evento.gara) or (self.is_inseritore(evento.gara) and evento.creatore == self)

    def can_create_gara(self):
        return self.has_perm("engine.change_gara")

class Gara(models.Model):
    """
    Modello che descrive una gara
    """
    nome = models.CharField(max_length=200, help_text="Nome della gara")
    inizio = models.DateTimeField(blank=True, null=True)
    durata = models.DurationField(default=timedelta(hours=2), help_text="Durata nel formato hh:mm:ss")
    n_blocco = models.PositiveSmallIntegerField(blank=True, null=True,  # Il valore NULL non fa bloccare mai il punteggio
                                                verbose_name="Parametro N",
                                                help_text="Numero di risposte esatte che bloccano il punteggio di un problema")
    k_blocco = models.PositiveSmallIntegerField(blank=True, null=True,  # Il valore NULL fa aumentare sempre il punteggio
                                                verbose_name="Parametro K",
                                                help_text="Numero di risposte errate che aumentano il punteggio di un problema")
    num_problemi = models.PositiveSmallIntegerField(default=20,
                                                    verbose_name="Problemi",
                                                    help_text="Numero di problemi")
    cutoff = models.PositiveSmallIntegerField(blank=True, null=True, help_text="Numero di squadre che passano")
    fixed_bonus = models.CharField(blank=True, max_length=100,
                                   default='20,15,10,8,6,5,4,3,2,1',
                                   validators=[all_nonnegative_validator],
                                   verbose_name="Bonus problema",
                                   help_text="Bonus per le prime squadre a risolvere un problema")
    super_mega_bonus = models.CharField(blank=True, max_length=100,
                                        default='100,60,40,30,20,10',
                                        validators=[all_nonnegative_validator],
                                        verbose_name="Bonus finale",
                                        help_text="Bonus per le prime squadre a risolvere tutti i problemi")
    jolly = models.BooleanField(default=True,
                                verbose_name="Jolly",
                                help_text="Possibilità di inserire un jolly")
    # testo = models.FileField(blank=True, null=True,
    #                          upload_to=get_file_path,
    #                          verbose_name="Testo",
    #                          help_text="Il testo dei problemi")
    testo = models.URLField(blank=True, null=True,
                            verbose_name="Testo",
                            help_text="Link al testo dei problemi")
    history = HistoricalRecords()

    #
    # Permessi
    #

    admin = models.ForeignKey(User, on_delete=models.CASCADE, related_name="administered_gare", null=True)
    inseritori = models.ManyToManyField(User, blank=True)

    class Meta:
        verbose_name_plural = "gare"

    def __str__(self):
        return self.nome

    """
    Definisce delle proprietà in modo da poter ottenere e settare direttamente
    degli array per i bonus di risoluzione dei problemi
    """

    def get_fixed_bonus_array(self):
        return str2arr(self.fixed_bonus)

    def set_fixed_bonus_array(self, array):
        self.fixed_bonus = ','.join(map(str, array))

    fixed_bonus_array = property(get_fixed_bonus_array, set_fixed_bonus_array)

    def get_super_mega_bonus_array(self):
        return str2arr(self.super_mega_bonus)

    def set_super_mega_bonus_array(self, array):
        self.super_mega_bonus = ','.join(map(str, array))

    super_mega_bonus_array = property(get_super_mega_bonus_array, set_super_mega_bonus_array)

    def get_ora_fine(self):
        if not self.inizio:
            return None
        return self.inizio + self.durata

    def finished(self):
        return (self.inizio is not None) and (timezone.now() > self.get_ora_fine())

    def get_all_eventi(self, user, squadra, problema, risposta):
        """Restituisce tutti gli eventi all'amministratore."""
        qs = self.eventi.all().select_related("consegna__squadra", "jolly__squadra")

        if user.can_administrate(self):
            
            res = [x.as_child() for x in qs]
            if squadra:
                res = [x for x in res if x.squadra.nome == squadra]
            if problema:
                res = [x for x in res if x.problema == int(problema)]
            if risposta:
                res = [x for x in res if x.risposta == int(risposta)]
            
            return res
        raise PermissionDenied("L'utente non può chiedere gli eventi della gara.")

    def get_eventi(self, user):
        """Restituisce gli eventi visualizzabili dall'utente."""
        qs = self.eventi.all().select_related("consegna__squadra", "jolly__squadra")

        if user.can_administrate(self):
            return [(True, x.as_child()) for x in qs[:20]]
        if user.is_inseritore(self):
            return [(x.creatore == self, x.as_child()) for x in qs[:20]]
        if user.is_consegnatore(self):
            return [(False, x.as_child()) for x in qs.filter(creatore=user)]
        raise PermissionDenied("L'utente non può chiedere gli eventi della gara.")

    def get_squadre_inseribili(self, user):
        '''Restiuisce le squadre per cui l'utente può effettuare una consegna.'''
        qs = self.squadre.all()
        if user.can_administrate(self) or user.is_inseritore(self):
            return qs
        else:
            qs = qs.filter(consegnatore=user)
            if qs.exists():
                return qs
            else:
                raise PermissionDenied("L'utente non può consegnare per nessuna squadra.")

    def get_soluzioni(self):
        sol = {}
        for s in self.soluzioni.all():
            sol[s.problema] = s.risposta
        return sol

    def get_problemi(self):
        problems = {}
        for s in self.soluzioni.all():
            problems[s.problema] = {"nome": s.nome, "punteggio": s.punteggio}
        return problems

    def get_consegne(self, last=None):
        sol = self.get_soluzioni()
        res = []
        qs = Consegna.objects.filter(gara=self).select_related('squadra')
        if last is not None:
            qs = qs.filter(pk__gt=last)

        # TODO: ottimizzare questa cosa, magari in una query
        for c in qs.order_by('orario'):
            tmp = {}
            tmp['id'] = c.pk
            tmp['squadra'] = c.squadra.num
            tmp['ospite'] = c.squadra.ospite
            tmp['orario'] = c.orario
            tmp['problema'] = c.problema
            tmp['giusta'] = (c.risposta == sol[c.problema])
            res.append(tmp)
        return res

    def get_jolly(self, last=None):
        res = []
        qs = Jolly.objects.filter(gara=self).select_related('squadra')
        if last is not None:
            qs = qs.filter(pk__gt=last)
        for c in qs.order_by('orario'):
            tmp = {}
            tmp["id"] = c.pk
            tmp["squadra"] = c.squadra.num
            tmp["problema"] = c.problema
            res.append(tmp)
        return res

    def get_squadre(self):
        res = {}
        for s in self.squadre.all():
            res[s.num] = {"nome": s.nome, "ospite": s.ospite}
        return res

    def get_squadre_order(self):
        return self.squadre.all().order_by('num')

    def get_last_update(self):
        """
        Metodo per vedere qual è stata l'ultima modifica sostanziale
        Restituisce il più recente tra:
        - Ultima modifica di gara
        - Ultima modifica o eliminazione di un jolly
        - Ultima modifica o eliminazione di una consegna
        - Ultima modifica di un problema
        """
        lu = self.history.latest().history_date
        try:

engine/forms.py
from django import forms
from engine.models import User
from django.contrib.auth.forms import UserCreationForm
from crispy_forms.helper import FormHelper

from engine.models import Squadra, Soluzione, Jolly, Consegna

class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')

class RispostaEsattaFormSet(forms.BaseModelFormSet):
    def __init__(self, *args, **kwargs):
        super(RispostaEsattaFormSet, self).__init__(*args, **kwargs)
        no_of_forms = len(self)
        for i in range(0, no_of_forms):
            self[i].fields['risposta'].label += " {}".format(i + 1)
            self[i].fields['problema'].widget = forms.HiddenInput()


RispostaFormset = forms.modelformset_factory(
    Soluzione, fields=('problema', 'risposta', 'nome', 'punteggio'),
    extra=0, formset=RispostaEsattaFormSet,)


class BaseSquadraFormSet(forms.BaseModelFormSet):
    def __init__(self, *args, **kwargs):
        users_qs = kwargs.pop("users_qs")
        super().__init__(*args, **kwargs)
        users_qs.all = lambda: users_qs
        users_qs.iterator = users_qs.all

        # Apply the common (non-cloning) querysets to all the forms
        for form in self.forms:
            form.fields["consegnatore"].queryset = users_qs

    def clean(self, *args, **kwargs):
        if any(self.errors):
            # Don't bother validating the formset unless each form is valid on its own
            return
        squadre = []
        ids = []
        for form in self.forms:
            id = form.cleaned_data["num"]
            sq = form.cleaned_data['nome']
            if sq in squadre:
                raise forms.ValidationError('I nomi delle squadre devono essere distinti!')
            if id in ids:
                raise forms.ValidationError('Gli identificativi delle squadre devono essere unici!')
            squadre.append(sq)
            ids.append(id)


class SquadraForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_class = 'form-inline'
        self.helper.field_template = 'forms/inline_field.html'

    class Meta:
        model = Squadra
        fields = ['num', 'nome', 'ospite', 'consegnatore']


SquadraFormset = forms.modelformset_factory(
                    Squadra, form=SquadraForm,
                    extra=0, formset=BaseSquadraFormSet,)


class SquadraChoiceField(forms.ModelChoiceField):
    def label_from_instance(self, obj):
        return obj.get_id_nome()


class InserimentoForm(forms.Form):
    problema = forms.IntegerField(min_value=1)
    risposta = forms.IntegerField(min_value=0, max_value=9999, required=False)
    jolly = forms.BooleanField(required=False)
    squadra = SquadraChoiceField(required=True, queryset=None)

    def __init__(self, *args, **kwargs):
        self.gara = kwargs.pop('gara', None)
        self.user = kwargs.pop('user', None)
        super(InserimentoForm, self).__init__(*args, **kwargs)
        if self.gara:
            self.fields['squadra'].queryset = self.gara.get_squadre_inseribili(self.user)
            self.fields['squadra'].empty_label = None
            self.fields['squadra'].widget.attrs.update({'autofocus': ''})

    def clean(self):
        cleaned_data = super().clean()
        if self.errors:
            return cleaned_data

        if bool(cleaned_data['jolly']) != bool(cleaned_data['risposta'] is None):
            raise forms.ValidationError('Inserire la risposta o il jolly, ma non entrambi')
        
        if bool(cleaned_data['jolly']) and Jolly.objects.filter(squadra = cleaned_data['squadra']).exists():
            raise forms.ValidationError('Ė già stato inserito un jolly per la squadra')
 
        obj = self.get_instance()
        obj.clean()
        return cleaned_data

    def get_instance(self):
        if self.cleaned_data.get('jolly'):
            return Jolly(gara=self.gara, squadra=self.cleaned_data.get('squadra'),
                         problema=self.cleaned_data.get('problema'))
        else:
            return Consegna(gara=self.gara, squadra=self.cleaned_data.get('squadra'),
                            problema=self.cleaned_data.get('problema'),
                            risposta=self.cleaned_data.get('risposta'))


class ModificaConsegnaForm(forms.Form):
    problema = forms.IntegerField(min_value=1, max_value=50)
    risposta = forms.IntegerField(min_value=0, max_value=9999)


class ModificaJollyForm(forms.Form):
    jolly = forms.IntegerField(min_value=1, max_value=50)


class UploadGaraForm(forms.Form):
    gara = forms.FileField(label="Gara", help_text="Scegli il file JSON contente la gara da importare")

engine/templates/about.html
{% extends "baseheader.html" %}

{% block title %}About{% endblock %}

{% block content %}
<h1>About</h1>

<p>Turing è un software open source per la gestione delle gare a squadre di Matematica.</p>
<p>Il nostro obiettivo è quello di rendere semplice e disponibile a tutti l'utilizzo di un motore per le gare a squadre. Sai che questo sito potrebbe girare senza problemi anche sul tuo computer?</p>

<h2>Il progetto</h2>

<p>
    Questo sito è sicuramente l'elemento più visibile di questo progetto, ma la parte fondamentale è la community che vorremmo creare.<br/>
    Puoi venirci a trovare:
    <ul>
        <li>su <a href="https://discord.gg/gMgJmPukUA" target="_blank">Discord</a>, per parlare con altri di Turing e di gare a squadre</li>
        <li>su <a href="https://gitlab.com/drago-96/turing" target="_blank">GitLab</a>, se sei interessato anche all'aspetto di sviluppo del programma</li>
    </ul>
</p>


<h2>Chi siamo</h2>

<p>Il team di sviluppatori è composto da Riccardo Zanotto, Matteo Migliorini, Federico Poloni, Matteo Protopapa e Matteo Rossi.</p>

{% endblock %}

engine/templates/base.html
<!DOCTYPE html>
<html lang="it">
{%load static%}
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
    <title>{% block title %}{% endblock %}</title>

    <!-- Bootstrap & jQuery -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'vendor/SB_Admin/css/sb-admin.css' %}" rel="stylesheet" type="text/css">


    <link href="{% static 'engine/css/main.css' %}" rel="stylesheet" type="text/css" >

    {% block css %}{% endblock %}
    {% block head %}{% endblock %}
</head>
<body class="d-flex flex-column min-vh-100">
  {% block header %}{% endblock %}
    <div class="flex-fill container-fluid">
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
              {{message}}
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            {% endfor %}
        </ul>
        {% endif %}
    {% block content %}{% endblock %}
    </div>
    {% block footer %}{% endblock %}
    <script>
    window.onerror = function(msg, url, linenumber) {
      alert('Error message: '+msg+'\nURL: '+url+'\nLine Number: '+linenumber);
      return true;
    }
    </script>
</body>
</html>

engine/templates/basegara.html
{% extends "baseheader.html" %}
{% block navitems %}
{% if object %}
<li class="nav-item dropdown">
  <a class="nav-link" href="{% url 'engine:gara-detail' object.pk %}">
    {{object.nome}} overview <i class="fas fa-home"></i>
  </a>
</li>
{% if not object.finished %}
<li class="nav-item dropdown">
    <a class="nav-link" href="{% url 'engine:inserimento' object.pk %}">
        Inserimento <i class="fas fa-edit"></i>
    </a>
</li>
{% endif %}
{% if object.inizio and gara.testo %}
<li class="nav-item dropdown">
    <a class="nav-link" href="{{gara.testo}}" target="_blank">
        Testo <i class="fas fa-file-pdf"></i>
    </a>
</li>
{% endif %}

<li class=" nav-item dropdown">
  <button type="button" class="btn nav-link dropdown-toggle" data-toggle="dropdown" aria-haspopup="true">
    Classifiche <i class="fas fa-bars" style="color:gray"></i>
  </button>
  <ul class="dropdown-menu dropdown-menu-right bg-dark text-white">
    <li><a class="text-white" href="{% url 'engine:classifica-squadre' object.pk %}" target="_blank">Squadre</a></li>
    <li><a class="text-white" href="{% url 'engine:classifica-problemi' object.pk %}" target="_blank">Problemi</a></li>
    <li><a class="text-white" href="{% url 'engine:classifica-stato' object.pk %}" target="_blank">Stato</a></li>
    {% if object.inizio is not null %}
    <li><a class="text-white" href="{% url 'engine:classifica-cronaca' object.pk %}" target="_blank">Telecronaca</a></li>
    <li><a class="text-white" href="{% url 'engine:classifica-unica' object.pk %}" target="_blank">Unica</a></li>
    {% endif %}
  </ul>
</li>
{% endif %}
{% endblock %}

engine/templates/baseheader.html
{% extends "base.html" %}
{%load static%}
{% block header %}
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
    <a class="navbar-brand mr-1 text-truncate" style="max-width:75%" href="/engine/">
        <img src="{% static 'logo.png' %}" class="img-thumbnail" style="height:2.5rem"></img>
        <span class="ml-2">Turing - Gestione Gara a Squadre</span>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto mr-0 mr-md-3 my-2 my-md-0">

          {% block navitems %}
          {% if gare_attive %}
          <li class="nav-item dropdown">
              <button type="button" class="btn nav-link dropdown-toggle" data-toggle="dropdown" aria-haspopup="true">
                Gare attive <i class="fas fa-bars" style="color:gray"></i>
              </button>
            <ul class="dropdown-menu dropdown-menu-right bg-dark text-white">
              {% for g in gare_attive %}
              <li><a class="text-white" href="{% url 'engine:gara-detail' g.pk %}">{{g}}</a></li>
              {% endfor %}
            </ul>
          </li>
          {% endif %}
          {% endblock %}

          <li class="nav-item dropdown">
            {% if user.is_authenticated %}
              <button type="button" class="btn nav-link dropdown-toggle" data-toggle="dropdown" aria-haspopup="true">
                {{ user.first_name }} <i class="fas fa-user" style="color:gray"></i>
              </button>
              <ul class="dropdown-menu dropdown-menu-right bg-dark text-white">
                {% if user.is_staff %}
                <li><a class="text-white" href="{% url 'admin:index' %}" target="_blank">Admin <i class="fas fa-user-circle"></i></a></li>
                {% endif %}
                {% if user.can_create_gara %}
                <li><a class="text-white" href="{% url 'engine:gara-new' %}">Nuova gara  <i class="fas fa-plus-circle"></i></a></li>
                {% endif %}
                <li><a class="text-white" href="{% url 'password_change' %}">Cambio password <i class="fas fa-key"></i></a></li>
                <li><a class="text-white" href="{% url 'logout' %}">Logout <i class="fas fa-sign-out-alt"></i></a></li>
              </ul>
            {% else %}
            {% if registration_open %}
              <a class="nav-link" href="{% url 'signup' %}">
                Registrati <i class="fas fa-user-plus"></i>
              </a>
              </li>
            {% endif %}
              <li class="nav-item dropdown">
              <a class="nav-link" href="{% url 'login' %}">
                Login <i class="fas fa-sign-in-alt"></i>
              </a>
            {% endif %}
          </li>
        </ul>
    </div>
  </nav>
{% endblock %}
{% block footer %}
    <footer class="font-small text-light bg-dark mt-3 py-1 pl-2">
        <div class="pull-left">
          Powered by <a href="{% url 'engine:about' %}">Turing</a>.
        </div>
    </footer>
{% endblock %}

engine/templates/index.html
{% extends "baseheader.html" %}

{% block title %}Turing homepage{% endblock %}

{% block content %}

{% if gare_attive %}
<div id="wrapper">
  <div class="card mb-3">
    <div class="card-header">
      <h5 class="pr-3"><i class="fas fa-table"></i>
      Gare in corso</h5>
    </div>
    <div class="card-body">
      <div class="table-responsive">
        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
          <thead>
            <tr>
              <th>Id</th>
              <th>Nome</th>
              <th>Testo</th>
              <th>Inizio</th>
              <th>Fine</th>
            </tr>
          </thead>
          <tbody>
              {% for gara in gare_attive %}
            <tr>
              <td>{{gara.pk}}</td>
              <td><a href="{% url 'engine:gara-detail' gara.pk%}">{{gara.nome}}</a></td>
              <td>{% if gara.testo %}<a href="{{gara.testo}}" target=_blank><i class="fas fa-file-pdf"></i></a>{% else %}<i class="fas fa-ban"></i>{% endif %}</td>
              <td>{{gara.inizio}}</td>
              <td>{{gara.get_ora_fine}}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
{% endif %}

<div id="wrapper">
  <div class="card mb-3">
    <div class="card-header">
      <div class="d-flex align-items-baseline justify-content-between">
        <h5 class="pr-3"><i class="fas fa-table"></i> Gare da iniziare</h5>
        {% if perms.engine.add_gara %}
          <div><a href="{% url 'engine:gara-new' %}" class="btn btn-primary">Crea nuova gara</a></div>
        {% endif %}
      </div>
    </div>
    <div class="card-body">
      <div class="table-responsive">
        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
          <thead>
            <tr>
              <th>Id</th>
              <th>Nome</th>
            </tr>
          </thead>
          <tbody>
              {% for gara in gare_da_iniziare %}
            <tr>
              <td>{{gara.pk}}</td>
              <td><a href="{% url 'engine:gara-detail' gara.pk%}">{{gara.nome}}</a></td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<div id="wrapper">
  <div class="card mb-3">
    <div class="card-header">
      <div class="d-flex align-items-baseline justify-content-between">
        <h5 class="pr-3"><i class="fas fa-table"></i> Archivio</h5>
        {% if perms.engine.add_gara %}
          <div><a href="{% url 'engine:gara-upload' %}" class="btn btn-primary">Importa gara</a></div>
        {% endif %}
      </div>
    </div>
      <div class="card-body">
        <div class="table-responsive">
          <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
            <thead>
              <tr>
                <th>Id</th>
                <th>Nome</th>
                <th>Inizio</th>
                <th>Fine</th>
                <th>Download</th>
              </tr>
            </thead>
            <tbody>
                {% for gara in gare_archivio %}
              <tr>
              <td>{{gara.pk}}</td>
              <td><a href="{% url 'engine:gara-detail' gara.pk%}">{{gara.nome}}</a></td>
                <td>{{gara.inizio}}</td>
                <td>{{gara.get_ora_fine}}</td>
                <td><a href="{% url 'engine:gara-download' gara.pk%}" target=_blank><i class="fas fa-download"></i></a></td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
  </div>
</div>
{% endblock %}